Abidi.Web/Areas/Admin/Controllers/PersonFilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Abidi.DataLayer.Context;
using Abidi.DataLayer.Models;

namespace Abidi.Web.Areas.Admin.Controllers
{
    public class PersonFilesController : Controller
    {
        private AbidiContext db = new AbidiContext();

        [Authorize]
        // GET: Admin/PersonFiles
        public ActionResult Index(int? id)
        {
            var personFiles = db.PersonFiles.Include(u => u.Person);
            return View(personFiles.Where(u => u.PersonId == id).ToList());
        }

        // GET: Admin/PersonFiles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PersonFile personFile = db.PersonFiles.Find(id);
            if (personFile == null)
            {
                return HttpNotFound();
            }
            return View(personFile);
        }

        // GET: Admin/PersonFiles/Create
        public ActionResult Create(int id)
        {
            ViewBag.PersonId = new SelectList(db.People.Where(u => u.Id == id), "Id", "FirstName");
            return View();
        }

        // POST: Admin/PersonFiles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FileId,PersonId,FileName,FileFormat,FileAddress")] PersonFile personFile, HttpPostedFileBase[] FileAddress)
        {
            if (ModelState.IsValid)
            {
                foreach (HttpPostedFileBase file in FileAddress)
                {
                    if (file != null)
                    {
                        personFile.FileName = Path.GetFileName(file.FileName);
                        personFile.FileFormat = Path.GetExtension(Path.GetFileName(file.FileName));

                        var InputFileName = Guid.NewGuid() + Path.GetExtension(Path.GetFileName(file.FileName));
                        var ServerSavePath = Path.Combine(Server.MapPath("~/UploadedFiles/") + InputFileName);
                        file.SaveAs(ServerSavePath);

                        personFile.FileAddress = "~/UploadedFiles/" + InputFileName;
                        //......در این بخش نام محل ذخیره عکس دریافت می شود

                        db.PersonFiles.Add(personFile);
                        db.SaveChanges();
                        ViewBag.UploadStatus = FileAddress.Count().ToString() + " با موفقیت آپلود شد";
                    }

                    //if (file != null && file.ContentLength > 0)
                    //{
                    //    personFile.FileName = Path.GetFileName(file.FileName);
                    //    personFile.FileFormat = Path.GetExtension(Path.GetFileName(file.FileName));
                    //    string[] allowedExtensions = { ".pdf", ".txt" };

                    //    if (allowedExtensions.Contains(personFile.FileFormat))
                    //    {
                    //        var maxFileSize = 500 * 1024; // 500KB
                    //        if (file.ContentLength > maxFileSize)
                    //        {
                    //            ViewBag.Message = "File size exceeds the maximum limit of 5MB.";
                    //            return View();
                    //        }
                    //    }

                    //    var InputFileName = Guid.NewGuid() + Path.GetExtension(Path.GetFileName(file.FileName));
                    //    var ServerSavePath = Path.Combine(Server.MapPath("~/UploadedFiles/") + InputFileName);
                    //    file.SaveAs(ServerSavePath);

                    //    personFile.FileAddress = "~/UploadedFiles/" + InputFileName;
                    //    //......در این بخش نام محل ذخیره عکس دریافت می شود

                    //    db.PersonFiles.Add(personFile);
                    //    db.SaveChanges();
                    //    ViewBag.UploadStatus = FileAddress.Count().ToString() + " با موفقیت آپلود شد";
                    //}

                }

                return RedirectToAction("Index", "People");
            }

            ViewBag.PersonId = new SelectList(db.People, "Id", "FirstName", personFile.PersonId);
            return View(personFile);
        }

        // GET: Admin/PersonFiles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PersonFile personFile = db.PersonFiles.Find(id);
            if (personFile == null)
            {
                return HttpNotFound();
            }
            ViewBag.PersonId = new SelectList(db.People, "Id", "FirstName", personFile.PersonId);
            return View(personFile);
        }

        // POST: Admin/PersonFiles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FileId,PersonId,FileName,FileFormat,FileAddress")] PersonFile personFile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(personFile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PersonId = new SelectList(db.People, "Id", "FirstName", personFile.PersonId);
            return View(personFile);
        }

        // GET: Admin/PersonFiles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PersonFile personFile = db.PersonFiles.Find(id);
            if (personFile == null)
            {
                return HttpNotFound();
            }
            return View(personFile);
        }

        // POST: Admin/PersonFiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PersonFile personFile = db.PersonFiles.Find(id);
            db.PersonFiles.Remove(personFile);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult DownloadFile(int id)
        {
            var filePerson = db.PersonFiles.Find(id);
            Session["FileAddress"] = filePerson.FileAddress.FirstOrDefault();
            return RedirectToAction("Index");
        }
    }
}

Abidi.Web/Areas/Admin/Views/PersonFiles/Create.cshtml
@model Abidi.DataLayer.Models.PersonFile

@{
    ViewBag.Title = "Create";
    Layout = null;
}

@using (Html.BeginForm("Create", "PersonFiles", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group" style="display:none">
            @Html.LabelFor(model => model.PersonId, "PersonId", htmlAttributes: new { @class = "control-label col-md-6" })
            <div class="col-md-12">
                @Html.DropDownList("PersonId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PersonId, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.FileName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FileName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FileFormat, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FileFormat, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FileFormat, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.FileAddress, htmlAttributes: new { @class = "control-label col-md-6" })
            <div class="col-md-12">
                @Html.TextBoxFor(model => model.FileAddress, "", new { @type = "file", @multiple = "multiple" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="آپلود فایل" class="btn btn-success" />
            </div>
        </div>
        @if
            (ViewBag.UploadStatus != null)
        {
            <div class="label label-success">ViewBag.UploadStatus</div>
        }
    </div>
}

<script src="~/Scripts/jquery-3.7.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Abidi.Web/Areas/Admin/Views/PersonFiles/Delete.cshtml
@model Abidi.DataLayer.Models.PersonFile

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PersonFile</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Person.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileFormat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileFormat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileAddress)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Abidi.Web/Areas/Admin/Views/PersonFiles/Details.cshtml
@model Abidi.DataLayer.Models.PersonFile

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>PersonFile</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Person.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileFormat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileFormat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileAddress)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.FileId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Abidi.Web/Areas/Admin/Views/PersonFiles/Edit.cshtml
@model Abidi.DataLayer.Models.PersonFile

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PersonFile</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.FileId)

        <div class="form-group">
            @Html.LabelFor(model => model.PersonId, "PersonId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PersonId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PersonId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileFormat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileFormat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileFormat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Abidi.Web/Areas/Admin/Views/PersonFiles/Index.cshtml
@model IEnumerable<Abidi.DataLayer.Models.PersonFile>

@{
	ViewBag.Title = "Index";
	Layout = null;
}

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
	<!--<tr>
	<th>
		@Html.DisplayNameFor(model => model.Person.FirstName)
	</th>
	<th>-->
	@*@Html.DisplayNameFor(model => model.FileName)*@
	<!--</th>
	<th>
		@Html.DisplayNameFor(model => model.FileFormat)
	</th>
	<th>
		@Html.DisplayNameFor(model => model.FileAddress)
	</th>
	<th></th>
	</tr>-->

	@foreach (var item in Model) {
		<tr>
			@*<td>
            @Html.DisplayFor(modelItem => item.User.Fname)
        </td>*@
			<td>
				@Html.DisplayFor(modelItem => item.FileName)
			</td>
			@*<td>
            @Html.DisplayFor(modelItem => item.FileFormat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FileAddress)
        </td>*@
			<td>
				@Html.ActionLink("دانلود فایل", "DownloadFile", "PersonFiles", new { id = item.FileId }, new { @class="btn btn-success btn-sm"})
				@*@Html.ActionLink("Edit", "Edit", new { id=item.FileId }) |
        @Html.ActionLink("Details", "Details", new { id=item.FileId }) |
        @Html.ActionLink("Delete", "Delete", new { id=item.FileId })*@
			</td>
		</tr>
	}

</table>